"""
toml_writer.py — scenario TOML serialiser for the BWSI mission builder
=======================================================================

Provides:
  write_toml(scenario_dict) → str   (complete TOML text ready to save)
  validate(scenario_dict)   → list[str]  (list of error messages; empty = OK)

The scenario_dict schema mirrors the TOML files consumed by gen_inspection.py,
gen_mcm.py, etc.  The builder web app constructs this dict from the user's
drawing session and calls write_toml() to persist it.

Supported mission types (scenario_dict["scenario"]["type"]):
  "inspection"  — pipeline survey (uses gen_inspection.py)
  "mcm"         — mine countermeasures (uses gen_mcm.py)
  "game"        — scavenger hunt (uses gen_mission.py)
  "gps_denied"  — GPS-denied beacon nav (uses gen_gps_denied.py)
"""

from __future__ import annotations

from typing import Any


# ---------------------------------------------------------------------------
# Primitive TOML emitters (no third-party dependency needed for writing)
# ---------------------------------------------------------------------------

def _indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def _toml_value(v: Any) -> str:
    """Serialise a Python value to its TOML literal representation."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, str):
        # Escape backslash and double-quote
        escaped = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(v, float):
        # Always include decimal point so TOML parses as float
        s = f"{v}"
        return s if "." in s or "e" in s else f"{v:.1f}"
    if isinstance(v, int):
        return str(v)
    raise TypeError(f"Cannot serialise {type(v).__name__} to TOML")


def _write_section(name: str, data: dict) -> list[str]:
    """Emit a [section] block."""
    lines = [f"[{name}]"]
    for k, v in data.items():
        lines.append(f"{k} = {_toml_value(v)}")
    return lines


def _write_array_of_tables(name: str, items: list[dict]) -> list[str]:
    """Emit an [[array.of.tables]] block for each item in the list."""
    lines = []
    for item in items:
        lines.append(f"[[{name}]]")
        for k, v in item.items():
            if isinstance(v, list):
                # Nested list (e.g., pipeline points) → inline TOML array
                inner = ", ".join(
                    f"[{p[0]}, {p[1]}]" if isinstance(p, (list, tuple)) else _toml_value(p)
                    for p in v
                )
                lines.append(f"{k} = [{inner}]")
            else:
                lines.append(f"{k} = {_toml_value(v)}")
        lines.append("")
    return lines


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_toml(scenario_dict: dict) -> str:
    """
    Serialise a scenario dict to a well-formatted TOML string.

    The dict should follow this schema (all optional keys shown):

    {
      "scenario": {
          "name": str,
          "description": str,
          "type": "inspection" | "mcm" | "game" | "gps_denied",
          "tiff_file": str,          # optional
      },
      "origin": {"lat": float, "lon": float},
      "arena": {"vertices": [[x,y], ...]},   # local XY metres

      # inspection only:
      "pipelines": [{"label": str, "depth": float, "points": [[x,y],...]}, ...],
      "anomalies": [{"pipeline": str, "x": float, "y": float, "type": str}, ...],

      # mcm only:
      "mines": [{"label": str, "x": float, "y": float, "type": "hazard"|"benign"}, ...],

      "sensor": {...},     # mission-type-specific sensor params
      "scoring": {...},
      "survey": {...},     # mcm only

      "teams": [
          {
              "name": str,
              "color": str,
              "vehicles": [
                  {
                      "name": str,
                      "student_mode": "python" | "cpp",
                      "start_x": float,
                      "start_y": float,
                      "start_heading": int,
                      "max_speed": float,
                  }
              ],
          }
      ],

      # optional:
      "deployment": {
          "shoreside_host": str,
          "vehicle_hosts": {"alpha": str, "bravo": str, ...},
      },
    }
    """
    lines: list[str] = []

    mission_type = scenario_dict.get("scenario", {}).get("type", "unknown")

    # ---- Header comment ----
    lines.append(f"# BWSI AUVC — {scenario_dict.get('scenario', {}).get('name', 'Mission')} scenario")
    lines.append(f"# Mission type: {mission_type}")
    lines.append(f"# Generated by the BWSI Mission Builder")
    lines.append("")

    # ---- [scenario] ----
    lines.extend(_write_section("scenario", scenario_dict["scenario"]))
    lines.append("")

    # ---- [origin] ----
    lines.extend(_write_section("origin", scenario_dict["origin"]))
    lines.append("")

    # ---- [arena] ----
    arena = scenario_dict["arena"]
    lines.append("[arena]")
    inner = ", ".join(f"[{v[0]}, {v[1]}]" for v in arena["vertices"])
    lines.append(f"vertices = [{inner}]")
    lines.append("")

    # ---- Mission-type-specific geometry ----
    if mission_type == "inspection":
        if "pipelines" in scenario_dict:
            lines.extend(_write_array_of_tables("pipelines", scenario_dict["pipelines"]))
        if "anomalies" in scenario_dict:
            lines.extend(_write_array_of_tables("anomalies", scenario_dict["anomalies"]))

    elif mission_type == "mcm":
        if "mines" in scenario_dict:
            lines.extend(_write_array_of_tables("mines", scenario_dict["mines"]))

    # For game / gps_denied, geometry is encoded in the teams section.

    # ---- [sensor] ----
    if "sensor" in scenario_dict:
        lines.extend(_write_section("sensor", scenario_dict["sensor"]))
        lines.append("")

    # ---- [scoring] ----
    if "scoring" in scenario_dict:
        lines.extend(_write_section("scoring", scenario_dict["scoring"]))
        lines.append("")

    # ---- [survey] (mcm only) ----
    if "survey" in scenario_dict:
        lines.extend(_write_section("survey", scenario_dict["survey"]))
        lines.append("")

    # ---- [[teams]] ----
    for team in scenario_dict.get("teams", []):
        lines.append(f"[[teams]]")
        lines.append(f"name  = {_toml_value(team['name'])}")
        lines.append(f"color = {_toml_value(team['color'])}")
        lines.append("")
        for vehicle in team.get("vehicles", []):
            lines.append(f"  [[teams.vehicles]]")
            for k, v in vehicle.items():
                lines.append(f"  {k:<13} = {_toml_value(v)}")
            lines.append("")

    # ---- [deployment] (optional) ----
    if "deployment" in scenario_dict:
        dep = scenario_dict["deployment"]
        lines.append("[deployment]")
        if "shoreside_host" in dep:
            lines.append(f"shoreside_host = {_toml_value(dep['shoreside_host'])}")
        lines.append("")
        if "vehicle_hosts" in dep:
            lines.append("[deployment.vehicle_hosts]")
            for team_name, ip in dep["vehicle_hosts"].items():
                lines.append(f"{team_name} = {_toml_value(ip)}")
            lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def validate(scenario_dict: dict) -> list[str]:
    """
    Validate a scenario dict.  Returns a list of human-readable error strings;
    an empty list means the scenario is valid.

    Checks:
      - Required top-level keys present
      - Origin lat/lon in range
      - Arena has at least 3 vertices
      - Mission-type geometry present
      - At least one team with at least one vehicle
      - Vehicle start positions inside the arena bounding box
      - No duplicate vehicle names
    """
    errors: list[str] = []

    # ---- Required top-level keys ----
    for key in ("scenario", "origin", "arena", "teams"):
        if key not in scenario_dict:
            errors.append(f"Missing required key: '{key}'")

    if errors:
        return errors   # can't proceed without the basics

    sc = scenario_dict["scenario"]
    if "name" not in sc:
        errors.append("scenario.name is required")

    mission_type = sc.get("type", "")
    valid_types  = ("inspection", "mcm", "game", "gps_denied")
    if mission_type not in valid_types:
        errors.append(f"scenario.type must be one of {valid_types}; got '{mission_type}'")

    # ---- Origin ----
    origin = scenario_dict["origin"]
    lat = origin.get("lat")
    lon = origin.get("lon")
    if lat is None or lon is None:
        errors.append("origin must have lat and lon")
    else:
        if not (-90 <= lat <= 90):
            errors.append(f"origin.lat {lat} out of range [-90, 90]")
        if not (-180 <= lon <= 180):
            errors.append(f"origin.lon {lon} out of range [-180, 180]")

    # ---- Arena ----
    vertices = scenario_dict["arena"].get("vertices", [])
    if len(vertices) < 3:
        errors.append("arena.vertices must have at least 3 points")
    else:
        for i, v in enumerate(vertices):
            if len(v) != 2:
                errors.append(f"arena.vertices[{i}] must be [x, y]; got {v}")

    # ---- Mission-type geometry ----
    if mission_type == "inspection":
        if not scenario_dict.get("pipelines"):
            errors.append("inspection mission requires at least one [[pipelines]] entry")
    elif mission_type == "mcm":
        mines = scenario_dict.get("mines", [])
        if not mines:
            errors.append("mcm mission requires at least one [[mines]] entry")
        else:
            for i, m in enumerate(mines):
                for k in ("label", "x", "y", "type"):
                    if k not in m:
                        errors.append(f"mines[{i}] missing key '{k}'")
                if m.get("type") not in ("hazard", "benign", None):
                    errors.append(f"mines[{i}].type must be 'hazard' or 'benign'")

    # ---- Teams ----
    teams = scenario_dict.get("teams", [])
    if not teams:
        errors.append("At least one [[teams]] entry is required")

    seen_vehicle_names: set[str] = set()
    for ti, team in enumerate(teams):
        if "name" not in team:
            errors.append(f"teams[{ti}] missing 'name'")
        vehicles = team.get("vehicles", [])
        if not vehicles:
            errors.append(f"teams[{ti}] ({team.get('name','?')}) has no vehicles")
        for vi, v in enumerate(vehicles):
            for k in ("name", "start_x", "start_y"):
                if k not in v:
                    errors.append(
                        f"teams[{ti}].vehicles[{vi}] missing '{k}'"
                    )
            vname = v.get("name", "")
            if vname in seen_vehicle_names:
                errors.append(f"Duplicate vehicle name '{vname}'")
            seen_vehicle_names.add(vname)

            # Check start position inside arena bounding box
            if vertices and "start_x" in v and "start_y" in v:
                xs = [p[0] for p in vertices]
                ys = [p[1] for p in vertices]
                sx, sy = v["start_x"], v["start_y"]
                margin = 5.0
                if not (min(xs) - margin <= sx <= max(xs) + margin):
                    errors.append(
                        f"Vehicle '{vname}' start_x={sx} is outside arena "
                        f"x range [{min(xs)}, {max(xs)}]"
                    )
                if not (min(ys) - margin <= sy <= max(ys) + margin):
                    errors.append(
                        f"Vehicle '{vname}' start_y={sy} is outside arena "
                        f"y range [{min(ys)}, {max(ys)}]"
                    )

    return errors


# ---------------------------------------------------------------------------
# Quick test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    example = {
        "scenario": {
            "name": "MCM Test",
            "type": "mcm",
            "description": "Quick test",
            "tiff_file": "MIT_SP.tif",
        },
        "origin": {"lat": 43.8253, "lon": -70.3304},
        "arena": {"vertices": [[-200, -300], [200, -300], [200, 0], [-200, 0]]},
        "mines": [
            {"label": "m01", "x": -80.0, "y": -150.0, "type": "hazard"},
            {"label": "m02", "x":  50.0, "y":  -80.0, "type": "benign"},
        ],
        "sensor": {"sensor_pd": 0.85, "sensor_pfa": 0.04},
        "scoring": {"penalty_missed_hazard": 150},
        "teams": [
            {
                "name": "alpha",
                "color": "dodger_blue",
                "vehicles": [
                    {"name": "jellyfish", "student_mode": "python",
                     "start_x": -150.0, "start_y": -20.0,
                     "start_heading": 180, "max_speed": 4.0},
                ],
            }
        ],
    }

    errs = validate(example)
    if errs:
        print("Validation errors:", errs)
    else:
        print("Validation: OK")
        print()
        print(write_toml(example))
